controller_joint_names: ['', 'turntable_lf_Joint', 'lf_1_Joint', 'lf_2_Joint', 'turntable_lb_Joint', 'lb_1_Joint', 'lb_2_Joint', 'turntable_rf_Joint', 'rf_1_Joint', 'rf_2_Joint', 'turntable_rb_Joint', 'rb_1_Joint', 'rb_2_Joint', ]
